name: UpdateLocalization

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  fetch-localization:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Fetch translations
        run: scripts/translations.sh
        env:
          LOKALIZE_TOKEN: ${{ secrets.LOKALIZE_TOKEN }}
      - name: Check for changes
        id: changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi
      - uses: maxim-lobanov/setup-xcode@v1
        if: steps.changes.outputs.has_changes == 'true'
        with:
          xcode-version: latest-stable
      - name: Post checkout pre
        if: steps.changes.outputs.has_changes == 'true'
        run: scripts/install-tuist.sh
      - name: Post checkout
        if: steps.changes.outputs.has_changes == 'true'
        run: scripts/post-checkout.sh
      - name: Build project
        if: steps.changes.outputs.has_changes == 'true'
        run: xcodebuild build -workspace Ugglan.xcworkspace -scheme Ugglan -destination 'platform=iOS Simulator,name=iPhone 16 Pro' CODE_SIGNING_ALLOWED=NO
      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Update localizations"
          title: "Update localizations"
          body: "This PR was created automatically to update localizations from Lokalise."
          branch: "update-localizations"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
